spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: localhost
      port: 6379
      username: ttrilha_app
      password: ttrilha123
      key-prefix: ttrilha_app_

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces   # Tempo OTLP HTTP port
  tracing:
    sampling:
      probability: 1.0

loki4j:
  url: http://localhost:3100   # Loki push API