services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: ttrilha-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - ttrilha-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  loki:
    image: grafana/loki:3.1.0
    container_name: ttrilha-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - ttrilha-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.5.0
    container_name: ttrilha-tempo
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml:ro
      - tempo_data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    networks:
      - ttrilha-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: ttrilha-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy
    networks:
      - ttrilha-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  prometheus_data:
    name: ttrilha_prometheus_data
  loki_data:
    name: ttrilha_loki_data
  tempo_data:
    name: ttrilha_tempo_data
  grafana_data:
    name: ttrilha_grafana_data

networks:
  ttrilha-network:
    name: ttrilha-network
    external: true
